/*DROP TABLE IF EXISTS EMPLOYEE;*/

/*CREATE TABLE EMPLOYEE(
ID INT NOT NULL AUTO_INCREMENT,
FULL_NAME VARCHAR(255) NOT NULL,
ROLE VARCHAR(255) NOT NULL,
SALARY DOUBLE NOT NULL,
PRIMARY KEY (ID)
);*/


INSERT INTO EMPLOYEE(FULL_NAME, ROLE, SALARY) VALUES ('Natalie Portman', 'Actress','8602.32');
INSERT INTO EMPLOYEE(FULL_NAME, ROLE, SALARY) VALUES ('Tom Hanks', 'Actor','9514.51');
INSERT INTO EMPLOYEE(FULL_NAME, ROLE, SALARY) VALUES ('Francis Ford Coppola', 'Director', '13000');
INSERT INTO EMPLOYEE(FULL_NAME, ROLE, SALARY) VALUES ('Al Pacino', 'Actor','9514.51');
INSERT INTO EMPLOYEE(FULL_NAME, ROLE, SALARY) VALUES ('Woody Allen', 'Director', '13000');
INSERT INTO EMPLOYEE(FULL_NAME, ROLE, SALARY) VALUES ('William Goldman', 'Screenwriter', '4437.50');
INSERT INTO EMPLOYEE(FULL_NAME, ROLE, SALARY) VALUES ('Robert De Niro', 'Actor','9514.51');